== Usage

To use this plugin, execute the `ngGenerateAll` command and pass the fully qualified path of a domain class.

[source,sh,indent="1"]
----
$ grails ngGenerateAll com.foo.Bar //or just Bar
----

You can also execute the command via Gradle.

[source,sh,indent="1"]
----
$ ./gradlew ngGenerateAll -Pargs="com.foo.Bar"
----

The default root path where assets will be created is "../client/src/app". That is because the plugin is configured by default to work with the angular2 profile which creates a multi-project build. To change that setting and others, see the link:configuration.html[configuration] section.


The command will generate everything required to create, read, update, and delete instances of domain classes with Angular 2. The following will be created if they don't already exist.

. A module for the domain `../client/src/app/bar/bar.module.ts`.
. A routing module `../client/src/app/bar/bar-routing.module.ts`.
. A javascript representation of the domain class `../client/src/app/bar/bar.ts`.
. A service to handle the CRUD of the domain `../client/src/app/bar/bar.service.ts`.
. Components for list, persist, and show `../client/src/app/bar/bar-show.component.ts`.
. Templates for the components.

Based on the properties of your domain, some other assets may be generated.

=== File Properties

If your domain contains a `byte[]`, `Byte[]`, or `java.sql.Blob`, the generated service will be modified to send a `FormData` instead of a standard JSON request body.

=== Associations

If your domain has associations to other domain classes, that will influence the scaffolding.

. A module will be created for the association.
. A service will be created to retrieve the list of the associated domain.
. A javascript representation of the associated domain class will be created.
. The associated module will be imported into the module of the domain class being rendered.

IMPORTANT: When generating assets for a domain class that already has a module created via an association, ensure you inform the command to overwrite.
[source,sh,indent="1"]
----
$ grails ngGenerateAll com.foo.Bar true
----

=== Bootstrap Module

If a file with the name "app.module.ts" exists in the base directory, the scaffolding will attempt to import the newly created module into it.

If that process is successful, you will see a message like "Added Bar as a dependency to your bootstrap module".

If it is not successful, you will be responsible for importing it.

=== Assumptions

This plugin assumes you have an environment that supports ES6 modules and typescript. It is based upon the angular2 profile which uses the Angular CLI.

=== REST API

The scaffolding generated by this plugin includes a service to interact with a REST resource for the given domain object.

The generated service assumes that the server offers an API using a standard REST pattern, as per the following example for a domain object mapped to the `/book` URL:

[options="header"]
|===
|Action |HTTP Method |URL
|List   |GET         |/book
|Create |POST        |/book
|Show   |GET         |/book/5
|Update |PUT         |/book/5
|Delete |DELETE      |/book/5
|===

==== Dates

In order for the scaffolding to work as designed, the databinding needs an additional date format to correctly parse date values sent by the client. The necessary format has been added by default in Grails 3.2.0.

Here is an example on how to configure the format.

[source,yaml,indent="1"]
.application.yml
----
grails:
    databinding:
        dateFormats:
            - "yyyy-MM-dd'T'HH:mm:ss.SSSX"
----

=== Routing

If you are using the angular2 profile, the default index page is modified so that clicking on the link to the controller will automatically route you to the module the controller represents. If you are using this plugin in an existing application, you will have a little bit of work to do to use the generated assets.

The first step is to ensure the module is included in the page. If the bootstrap module is found, a dependency will automatically be created, however if the bootstrap module is not found, it is up to you to ensure the newly created module is imported.


The following routes are defined in the generated routing modules:

[source,javascript]
----
  {path: 'domain', redirectTo: 'domain/list', pathMatch: 'full'},
  {path: 'domain/list', component: DomainListComponent},
  {path: 'domain/create', component: DomainPersistComponent},
  {path: 'domain/edit/:id', component: DomainPersistComponent},
  {path: 'domain/show/:id', component: DomainShowComponent}
----

Assuming the modules has been loaded on the index page and there is a `<router-outlet></router-outlet>` directive on the index page, the URL would be `http://localhost:8080/#/domain`. See the documentation for the link:https://angular.io/docs/ts/latest/guide/router.html[Angular Router] for more information.

